with open("file1.txt") as f:
    print("\ncursor at start of file (default):")
    print(f.read())
    print("\ncursor at the end of file:")
    print(f.read())
    print("\nseek to 0:")
    f.seek(0)
    print(f.read())
    f.seek(0)
    print("\nread the 1st line:")
    print(f.readline())
    print("\nread the 2nd line:")
    print(f.readline())
    f.seek(0)
    print("\nuse readlines() that returns a list:")
    print(type(f.readlines()))
    f.seek(0)
